import type { HistoryDetail } from "../types/api";

function formatVisitDate(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  return d.toLocaleString(undefined, {
    dateStyle: "long",
    timeStyle: "short",
  });
}

export function buildVisitSummaryText(detail: HistoryDetail): string {
  const lines: string[] = [
    "Medical Avatar Assistant — Visit Summary",
    "========================================",
    "",
    `Date: ${formatVisitDate(detail.startedAt)}`,
    `Specialty: ${detail.specialtyLabel}`,
    `Assistant: ${detail.agentLabel}`,
    "",
    "Summary",
    "-------",
    detail.summary.trim(),
  ];

  if (detail.topics.length > 0) {
    lines.push("", "Topics discussed", "----------------");
    for (const topic of detail.topics) {
      lines.push(`• ${topic}`);
    }
  }

  if (detail.adviceGiven.length > 0) {
    lines.push("", "Guidance provided", "-----------------");
    for (const advice of detail.adviceGiven) {
      lines.push(`• ${advice}`);
    }
  }

  if (detail.followUp?.trim()) {
    lines.push("", "Follow-up", "---------", detail.followUp.trim());
  }

  lines.push(
    "",
    "---",
    "This summary was generated by an AI assistant and is not medical advice.",
    "Always consult a qualified healthcare provider for diagnosis and treatment.",
  );

  return lines.join("\n");
}

export function downloadVisitSummary(detail: HistoryDetail): void {
  const text = buildVisitSummaryText(detail);
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const datePart = detail.startedAt.slice(0, 10);
  const filename = `visit-summary-${datePart}-${detail.consultationId.slice(0, 8)}.txt`;

  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.rel = "noopener";
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}
